# Generated by Django 5.2.13 on 2026-04-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ORG", "ORGANIZER"), ("PRT", "PARTICIPANT")],
                        default="ORG",
                        max_length=3,
                    ),
                ),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("PND", "PENDING"),
                            ("ACC", "ACCEPTED"),
                            ("DEC", "DECLINED"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="core.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
