# Generated by Django 5.2.13 on 2026-05-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_meetingparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingparticipant",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="role",
            field=models.CharField(
                choices=[("ORG", "ORGANIZER"), ("PRT", "PARTICIPANT")],
                default="PRT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="unique_meeting_participant"
            ),
        ),
    ]
