# Generated by Django 5.2.14 on 2026-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_timeslotresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
