# Generated by Django 5.2.14 on 2026-06-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_meeting_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslotresponse",
            name="response",
            field=models.CharField(
                choices=[("ACC", "ACCEPTED"), ("REJ", "REJECTED")],
                default="MAY",
                max_length=3,
            ),
        ),
    ]
