# Generated by Django 5.2.15 on 2026-06-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.meeting",
            ),
        ),
    ]
