# Generated by Django 5.2.16 on 2026-07-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_conversation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.conversation",
            ),
        ),
    ]
