STATUS_CHOICES = [
    ("DRF", "DRAFT"),
    ("PEN", "PENDING"),
    ("CNF", "CONFIRMED"),
    ("CNC", "CANCELLED"),
]


ROLE_CHOICES = [("ORG", "ORGANIZER"), ("PRT", "PARTICIPANT")]


INVITATION_CHOICES = [("PND", "PENDING"), ("ACC", "ACCEPTED"), ("DEC", "DECLINED")]
